document.addEventListener('DOMContentLoaded', function () {
  var searchInput = document.getElementById('search');
  var tableBody = document.getElementById('table-body');

  var tableData = [
    {"product": "AC 800M", "vendor": "ABB", "type": "Controller", "credentials": "service:ABB800xA"},
    {"product": "SREA-01", "vendor": "ABB", "type": "Ethernet Adapter Module", "credentials": "admin:admin"},
    {"product": "RTU500", "vendor": "ABB", "type": "Ethernet Adapter Module", "credentials": "admin:admin"},
    {"product": "netCADOPS Web Application", "vendor": "ABB", "type": "Software", "credentials": "0"},
    {"product": "Ellipse", "vendor": "ABB", "type": "Software", "credentials": "0"},
    {"product": "ATI Emergency Mass Notification Systems", "vendor": "Acoustic Technology, Inc. (ATI Systems)", "type": "Software", "credentials": "0"},
    {"product": "A850 Telemetry Gateway", "vendor": "Adcon Telemetry", "type": "Base Station", "credentials": "root:840sw"},
    {"product": "A850 Telemetry Gateway (ver2)", "vendor": "Adcon Telemetry", "type": "Base Station", "credentials": "root:840sw"},
    {"product": "A440 Wireless Modem", "vendor": "Adcon Telemetry", "type": "Base Station", "credentials": "root:840sw"},
    {"product": "addVANTAGE Pro 6.1, 6.5", "vendor": "Adcon Telemetry", "type": "HMI", "credentials": "root:root"},
    {"product": "SNMP-1000, MIC-3924", "vendor": "Advantech", "type": "system management module, intelligent chassis management module", "credentials": "advantech:admin"},
    {"product": "Advantech WebAccess browser-based HMI and SCADA software", "vendor": "Advantech", "type": "browser-based HMI and SCADA software", "credentials": "admin:blank"},
    {"product": "EKI-7659C", "vendor": "Advantech", "type": "industrial switch", "credentials": "admin:admin"},
    {"product": "EKI-7657C", "vendor": "Advantech", "type": "industrial switch", "credentials": "admin:admin"},
    {"product": "ADAM-6200 Series", "vendor": "Advantech", "type": "Intelligent Ethernet I/O Module", "credentials": "root:00000000"},
    {"product": "ADAM-6050W", "vendor": "Advantech", "type": "I/O module", "credentials": "root:00000000"},
    {"product": "ADAM-3600-A1F", "vendor": "Advantech", "type": "Remote I/O Module", "credentials": "Root:00000000, Admin:00000000, User:00000000"},
    {"product": "OmniSwitch 6250", "vendor": "Alcatel-Lucent", "type": "switch", "credentials": "admin:switch"},
    {"product": "AT-IE200-6GT (IE200 Series)", "vendor": "Allied Telesis", "type": "Industrial Ethernet Switches", "credentials": "manager:friend"},
    {"product": "AT-IE200-6GP (IE200 Series)", "vendor": "Allied Telesis", "type": "Industrial Ethernet Switches", "credentials": "manager:friend"},
    {"product": "AT-IE200-6FT (IE200 Series)", "vendor": "Allied Telesis", "type": "Industrial Ethernet Switches", "credentials": "manager:friend"},
    {"product": "AT-IE200-6FP (IE200 Series)", "vendor": "Allied Telesis", "type": "Industrial Ethernet Switches", "credentials": "manager:friend"},
    {"product": "KVGC202/EN/M/E11", "vendor": "Alstom", "type": "Relays", "credentials": "AAAA"},
    {"product": "MiCOM P141/P142/P143/P342/P343/P344/P345/P346/P391", "vendor": "Alstom", "type": "Relays", "credentials": "AAAA"},
    {"product": "Argus Messenger", "vendor": "Argus", "type": "Messenger", "credentials": "ArgusAdmin:masterkey"},
    {"product": "Argus Address Manager", "vendor": "Argus", "type": "Address Manager Software", "credentials": "argus:argus"},
    {"product": "ASTUTE140 Meter", "vendor": "Astute Medical", "type": "Analyzer", "credentials": "1234:1234"},
    {"product": "CR10 v2", "vendor": "B&B ELECTRONICS", "type": "Industrial router", "credentials": "root:root"},
    {"product": "Conel 4.0.1", "vendor": "B&B ELECTRONICS", "type": "Industrial router", "credentials": "root:root"},
    {"product": "SPECTRE Router", "vendor": "B&B ELECTRONICS", "type": "Router", "credentials": "root:root"},
    {"product": "ER75i", "vendor": "B&B ELECTRONICS", "type": "Industrial router", "credentials": "root:root"},
    {"product": "ER 75i DUO", "vendor": "B&B ELECTRONICS", "type": "Industrial router", "credentials": "root:root"},
    {"product": "ER 75i SL", "vendor": "B&B ELECTRONICS", "type": "Industrial router", "credentials": "root:root"},
    {"product": "ER75i v2", "vendor": "B&B ELECTRONICS", "type": "Industrial router", "credentials": "root:root"},
    {"product": "LR77 v2 Libratum/LR77 v2", "vendor": "B&B ELECTRONICS", "type": "Industrial router", "credentials": "root:root"},
    {"product": "UR5i v2", "vendor": "B&B ELECTRONICS", "type": "Industrial router", "credentials": "root:root"},
    {"product": "UCR11-v2", "vendor": "B&B ELECTRONICS", "type": "Industrial router", "credentials": "root:root"},
    {"product": "UCR11 v2 SL", "vendor": "B&B ELECTRONICS", "type": "Industrial router", "credentials": "root:root"},
    {"product": "XR5i v2E", "vendor": "B&B ELECTRONICS", "type": "Industrial router", "credentials": "root:root"},
    {"product": "XR5i v2", "vendor": "B&B ELECTRONICS", "type": "Industrial router", "credentials": "root:root"},
    {"product": "XR5i", "vendor": "B&B ELECTRONICS", "type": "Industrial router", "credentials": "root:root"},
    {"product": "XR5i SL", "vendor": "B&B ELECTRONICS", "type": "Industrial router", "credentials": "root:root"},
    {"product": "ES1A", "vendor": "B&B ELECTRONICS", "type": "Converter", "credentials": "root:dbps"},
    {"product": "Vlinx VESR4x4", "vendor": "B&B ELECTRONICS", "type": "SERIAL SERVER", "credentials": ""},
    {"product": "Vlinx MESR9xx Modbus Gateway", "vendor": "B&B ELECTRONICS", "type": "Modbus Gateway", "credentials": ""},
    {"product": "MediCal QAWeb Agent", "vendor": "Barco", "type": "Client Application", "credentials": "Advanced:advanced"},
    {"product": "IPC@CHIP", "vendor": "Beck IPC", "type": "PLC", "credentials": "PPPSERVER:, ppps:ppps"},
    {"product": "CX5020", "vendor": "Beckhoff Automation GmbH", "type": "PLC", "credentials": "webguest:1"},
    {"product": "TwinCAT", "vendor": "Beckhoff Automation GmbH", "type": "Software for the Windows control and automation technology", "credentials": "Administrator:1"},
    {"product": "BinTec X1200 II", "vendor": "BinTec Elmeg", "type": "Router", "credentials": "admin:bintec,"},
    {"product": "any routers", "vendor": "BinTec Elmeg", "type": "Router", "credentials": "(##unknown - means not known or any char):, ##unknown:snmp-Trap , suggested:, admin:1234, admin:password, admin:admin"},
    {"product": "BinTec R230aw", "vendor": "BinTec Elmeg", "type": "Router", "credentials": "admin:funkwerk"},
    {"product": "Bintec W2002T-n", "vendor": "BinTec Elmeg", "type": "WLAN Access Point for applications in rolling stocks", "credentials": "admin:funkwerk, admin:admin"},
    {"product": "bk3000", "vendor": "BK Ultrasound", "type": "Ultrasound System", "credentials": "administrator:superuser"},
    {"product": "easy/easy compact/easy split", "vendor": "CAREL", "type": "Electronic Microprocessor Controllers, plug-in electronic digital thermostat", "credentials": "22 (access to the parameters)"},
    {"product": "PJ32V/PJ32W/PJ32Z", "vendor": "CAREL", "type": "Electronic Microprocessor Controllers, plug-in electronic digital thermostat", "credentials": "22 (access to the parameters)"},
    {"product": "pCOWeb", "vendor": "CAREL", "type": "Communication Card", "credentials": "root:froot,\n    carel:fcarel, guest:fguest, httpadmin:fhttpadmin (ftp), admin:fadmin \n    (http), passwordless accounts via telnet: http::48:48:HTTP \n    users:/usr/http/root:/bin/bash, \n    nobody::99:99:nobody:/var/lib/nobody:/bin/bash"},
    {"product": "ir33 (ir33 platform)", "vendor": "CAREL", "type": "Integrated Electronic Microprocessor Controllers with LED display", "credentials": "22 (access to the parameters), 66 (download activation password)"},
    {"product": "ir33 power (ir33 platform)", "vendor": "CAREL", "type": "Integrated Electronic Microprocessor Controllers with LED display", "credentials": "22 (access to the parameters), 66 (download activation password)"},
    {"product": "ir33 DIN (ir33 platform)", "vendor": "CAREL", "type": "Integrated Electronic Microprocessor Controllers with LED display", "credentials": "22 (access to the parameters), 66 (download activation password)"},
    {"product": "powercompact (ir33 platform)", "vendor": "CAREL", "type": "Integrated Electronic Microprocessor Controllers with LED display", "credentials": "22 (access to the parameters), 66 (download activation password)"},
    {"product": "powercompact small (ir33 platform)", "vendor": "CAREL", "type": "Integrated Electronic Microprocessor Controllers with LED display", "credentials": "22 (access to the parameters), 66 (download activation password)"},
    {"product": "mastercella (ir33 platform)", "vendor": "CAREL", "type": "Integrated Electronic Microprocessor Controllers with LED display", "credentials": "22 (access to the parameters), 66 (download activation password)"},
    {"product": "Universal Infrared Series", "vendor": "CAREL", "type": "Pressure, Humidity and Temperature controllers", "credentials": "22 (enter and modify parameters C0, C13, 15 and 16 in addition to all ???P??? parameters), 77 (enter and modify all parameters)"},
    {"product": "IR33-DN33 Universale series", "vendor": "CAREL", "type": "Pressure, Humidity and Temperature controllers", "credentials": "77 (Setting type c, d, F parameters)"},
    {"product": "pRack PR100", "vendor": "CAREL", "type": "Compressor Rack Controller", "credentials": "user password: 0000, service  password: 1234, manufacturer password: 1234"},
    {"product": "humiSteam x-plus", "vendor": "CAREL", "type": "Humidifiers", "credentials": "77"},
    {"product": "PlantVisorPRO Locale", "vendor": "CAREL", "type": "Plant supervision", "credentials": "admin:admin"},
    {"product": "PlantWatchPRO", "vendor": "CAREL", "type": "Supervisor for small-medium installations", "credentials": "PVRemote:PD35010 (from a remote PC via a telephone connection)"},
    {"product": "mC2SE", "vendor": "CAREL", "type": "Electronic Controller", "credentials": "Direct level: \n    , user level: 22, super user level: 11, factory level: 66"},
    {"product": "PowerSoft", "vendor": "Carlo Gavazzi", "type": "Modular Software", "credentials": "admin:admin, user:user"},
    {"product": "In-Row M52 Microprocessor", "vendor": "ClimateWorx International", "type": "Controller", "credentials": "1024 (Service level)"},
    {"product": "M52 Microprocessor", "vendor": "ClimateWorx International", "type": "Controller", "credentials": "Level 1: 1024, level 2: 4321, level 3: 1234"},
    {"product": "ClinicPro EMR", "vendor": "ClinicPro", "type": "Electronic Medical / Health Records Software", "credentials": "admin:abc123"},
    {"product": "E-Series EEG (Siesta and Safiro data acquisition systems and the ProFusion EEG data acquisitionand analysis software)", "vendor": "Compumedics", "type": "Electroencephalograph Systems,data acquisition systems, HMI software", "credentials": "0000 (security dialogue password)"},
    {"product": "E-Series EEG/PSG (Siesta and Safiro data acquisition systems and the ProFusion EEG data acquisitionand analysis software)", "vendor": "Compumedics", "type": "Electroencephalograph Systems,data acquisition systems, HMI software", "credentials": "0000 (security dialogue password)"},
    {"product": "BASRT-B", "vendor": "Contemporary Control Systems", "type": "Router", "credentials": "admin:admin"},
    {"product": "UR5i", "vendor": "Datasensor", "type": "Router", "credentials": "root:root"},
    {"product": "UR5i SL", "vendor": "Datasensor", "type": "Router", "credentials": "root:root"},
    {"product": "S/5 Light Monitor", "vendor": "Datex-Ohmeda", "type": "Portable vital signs monitor", "credentials": "16/04/1934"},
    {"product": "AWC 500", "vendor": "Deif", "type": "Advanced Wind turbine Controller", "credentials": "root:deif7800 (administrator), default:1234 (user)"},
    {"product": "Delta Industrial Automation DOPSoft", "vendor": "Delta Electronics", "type": "Software", "credentials": "0"},
    {"product": "Delta Industrial Automation Screen Editor", "vendor": "Delta Electronics", "type": "Software", "credentials": "0"},
    {"product": "DC-ME-01T-S", "vendor": "Digi", "type": "Networking Modules", "credentials": "root:dbps"},
    {"product": "Digi Connect SP", "vendor": "Digi", "type": "Network Device Server Module", "credentials": "root:dbps"},
    {"product": "Digi Connect Wi-SP", "vendor": "Digi", "type": "Network Device Server Module", "credentials": "root:dbps"},
    {"product": "Digi Connect ME", "vendor": "Digi", "type": "Network Device Server Module", "credentials": "root:dbps"},
    {"product": "Digi Connect ME 4 MB", "vendor": "Digi", "type": "Network Device Server Module", "credentials": "root:dbps"},
    {"product": "Digi Connect Wi-ME", "vendor": "Digi", "type": "Network Device Server Module", "credentials": "root:dbps"},
    {"product": "Digi Connect EM", "vendor": "Digi", "type": "Network Device Server Module", "credentials": "root:dbps"},
    {"product": "Digi Connect Wi-EM", "vendor": "Digi", "type": "Network Device Server Module", "credentials": "root:dbps"},
    {"product": "Digi Connect ES 4/8 SB with Switch", "vendor": "Digi", "type": "Concentrator", "credentials": "root:dbps"},
    {"product": "Digi Connect ES 4/8 SB", "vendor": "Digi", "type": "Concentrator", "credentials": "root:dbps"},
    {"product": "ConnectPort TS 4x4", "vendor": "Digi", "type": "Terminal Server", "credentials": "root:dbps"},
    {"product": "ConnectPort TS 4x2", "vendor": "Digi", "type": "Terminal Server", "credentials": "root:dbps"},
    {"product": "ConnectPort TS W", "vendor": "Digi", "type": "Terminal Server", "credentials": "root:dbps"},
    {"product": "ConnectPort TS 8", "vendor": "Digi", "type": "Terminal Server", "credentials": "root:dbps"},
    {"product": "ConnectPort TS 8 MEI", "vendor": "Digi", "type": "Terminal Server", "credentials": "root:dbps"},
    {"product": "ConnectPort TS 16", "vendor": "Digi", "type": "Terminal Server", "credentials": "root:dbps"},
    {"product": "Digi Connect WAN", "vendor": "Digi", "type": "Industrial router", "credentials": "root:dbps"},
    {"product": "Digi Connect WAN GPRS", "vendor": "Digi", "type": "Industrial router", "credentials": "root:dbps"},
    {"product": "Digi Connect WAN GSM-R", "vendor": "Digi", "type": "Industrial router", "credentials": "root:dbps"},
    {"product": "Digi Connect WAN VPN", "vendor": "Digi", "type": "Industrial router", "credentials": "root:dbps"},
    {"product": "Digi Connect WAN IA", "vendor": "Digi", "type": "Industrial router", "credentials": "root:dbps"},
    {"product": "Digi Connect WAN 3G", "vendor": "Digi", "type": "Industrial router", "credentials": "root:dbps"},
    {"product": "Digi Connect WAN 3G IA", "vendor": "Digi", "type": "Industrial router", "credentials": "root:dbps"},
    {"product": "Digi Connect WAN 4G", "vendor": "Digi", "type": "Industrial router", "credentials": "root:dbps"},
    {"product": "Digi TransPort WR21", "vendor": "Digi", "type": "Industrial router", "credentials": "username:password"},
    {"product": "Digi TransPort WR44", "vendor": "Digi", "type": "Industrial router", "credentials": "username:password"},
    {"product": "Digi CM", "vendor": "Digi", "type": "Industrial router", "credentials": "root:dbps"},
    {"product": "DigiOne IAP Serial", "vendor": "Digi", "type": "Gateway", "credentials": "root:dbps"},
    {"product": "i.LON SmartServer", "vendor": "Echelon", "type": "Programmable Modules", "credentials": "for ftp and lns servers: ilon:ilon"},
    {"product": "i.LON SmartServer", "vendor": "Echelon", "type": "Building Energy Management Solution, LonWorks/IP Server, Internet Server", "credentials": "ilon:ilon"},
    {"product": "i.LON SmartServer 2.0", "vendor": "Echelon", "type": "Building Energy Management Solution, LonWorks/IP Server, Internet Server", "credentials": "ilon:ilon"},
    {"product": "i.LON 600", "vendor": "Echelon", "type": "Building Energy Management Solution, LonWorks/IP Server, Internet Server", "credentials": "ilon:ilon"},
    {"product": "i.LON 100e4", "vendor": "Echelon", "type": "Building Energy Management Solution, LonWorks/IP Server, Internet Server", "credentials": "ilon:ilon"},
    {"product": "LumInsight", "vendor": "Echelon", "type": "Central Management System", "credentials": "Echelon:echeloncorp"},
    {"product": "Nexus 1500", "vendor": "Electro Industries/GaugeTech", "type": "Power Quality Meter", "credentials": "anonymous:anonymous"},
    {"product": "Nexus 1500+", "vendor": "Electro Industries/GaugeTech", "type": "Power Quality Meter", "credentials": "anonymous:anonymous"},
    {"product": "Communicator EXT 3.0", "vendor": "Electro Industries/GaugeTech", "type": "Power Monitoring Software", "credentials": "eignet:inp100"},
    {"product": "AMS Suit", "vendor": "Emerson", "type": "diagnostic software", "credentials": "admin:\n    , sa:42Emerson42Eme (SQL Server)"},
    {"product": "DeltaV Digital Automation System", "vendor": "Emerson", "type": "Automation System", "credentials": "Administrator:deltav"},
    {"product": "Liebert IntelliSlot Web Card", "vendor": "Emerson", "type": "Web Card", "credentials": "Liebert:Liebert, User:User"},
    {"product": "Liebert OpenComms Web Card", "vendor": "Emerson", "type": "Web Card", "credentials": "Liebert:Liebert"},
    {"product": "Smart Wireless Gateway 1420", "vendor": "Emerson", "type": "Wireless Gateway", "credentials": "admin:default, maint:default, oper:default, exec:default"},
    {"product": "Smart Wireless Navigator", "vendor": "Emerson", "type": "stand-alone network infrastructure management tool", "credentials": "for\n    the Windows log in Administrator:navigator, for Smart Wireless \n    Navigator log in Supervisor:Admin, User1:Password1, User2:Password2, \n    User3:Password3"},
    {"product": "Network Power MPH2 Rack PDU", "vendor": "Emerson", "type": "Rack PDUs", "credentials": "admin:admin"},
    {"product": "UL33 UPS", "vendor": "Emerson", "type": "UPS", "credentials": "123456"},
    {"product": "Control Link Refrigeration System Controller", "vendor": "Emerson", "type": "Controller", "credentials": "0"},
    {"product": "UltraSite", "vendor": "Emerson", "type": "Software", "credentials": "User 01:100, User 05:200, User 09:300, Engineer:400"},
    {"product": "Avocent ACS 6000 Advanced Console Server", "vendor": "Emerson", "type": "Console Server", "credentials": "admin:avocent, root:linux"},
    {"product": "ROCLINK 800", "vendor": "Emerson", "type": "Software", "credentials": "LOI:1000"},
    {"product": "ControlWave Micro Quick", "vendor": "Emerson", "type": "PLC", "credentials": "for download project:, SYSTEM:666666"},
    {"product": "IP-KVM Avocent MergePoint Unity", "vendor": "Emerson", "type": "Switch", "credentials": "Admin:blank"},
    {"product": "Ovation DCS", "vendor": "Emerson", "type": "Switch for Distributed Control System", "credentials": "wdpf"},
    {"product": "Ovation DCS", "vendor": "Emerson", "type": "Switch for Distributed Control System", "credentials": "SNMP community string: wdpfRO"},
    {"product": "ControlWave Micro Process Automation Controller", "vendor": "Emerson", "type": "PLC", "credentials": "0"},
    {"product": "Fieldgate FXA520", "vendor": "Endress+Hauser", "type": "Gateway for remote monitoring and diagnosis", "credentials": "super:super"},
    {"product": "Fieldgate Viewer", "vendor": "Endress+Hauser", "type": "HMI software", "credentials": "admin:0000"},
    {"product": "EMG-10", "vendor": "ENTES", "type": "MODBUS Gateway", "credentials": "emg12 (for EMG12), emg10 (for EMG10), emg02 (for EMG02)"},
    {"product": "EMG-02", "vendor": "ENTES", "type": "MODBUS Gateway", "credentials": "emg12 (for EMG12), emg10 (for EMG10), emg02 (for EMG02)"},
    {"product": "EMG-12", "vendor": "ENTES", "type": "MODBUS Gateway", "credentials": "emg12 (for EMG12), emg10 (for EMG10), emg02 (for EMG02)"},
    {"product": "DTR-10", "vendor": "ENTES", "type": "time relay", "credentials": "0"},
    {"product": "MCB-125", "vendor": "ENTES", "type": "time relay", "credentials": "0"},
    {"product": "MCB-126", "vendor": "ENTES", "type": "time relay", "credentials": "0"},
    {"product": "MPR-53CS", "vendor": "ENTES", "type": "network analyzer", "credentials": "0"},
    {"product": "GEM-05", "vendor": "ENTES", "type": "GPRS/Modbus Gateway", "credentials": "gem10"},
    {"product": "GEM-10", "vendor": "ENTES", "type": "GPRS/Modbus Gateway", "credentials": "gem10"},
    {"product": "GEM-10SH", "vendor": "ENTES", "type": "GPRS/Modbus Gateway", "credentials": "gem10"},
    {"product": "ENTBUS PLUS", "vendor": "ENTES", "type": "Energy Management Software", "credentials": "admin:1234"},
    {"product": "EPM-04/04C/04CS", "vendor": "ENTES", "type": "MULTIMETER", "credentials": "0"},
    {"product": "MPR-SW", "vendor": "ENTES", "type": "Monitoring & Reporting Software", "credentials": "admin:"},
    {"product": "All", "vendor": "eWON", "type": "Router", "credentials": "adm:adm"},
    {"product": "USHA", "vendor": "Falcon", "type": "UPS SNMP HTTP AGENT", "credentials": "USHA:admin"},
    {"product": "V-Server VPR", "vendor": "Fuji Electric", "type": "Software", "credentials": "0"},
    {"product": "D60 Line Distance Relay", "vendor": "GE", "type": "RTU", "credentials": "0"},
    {"product": "Sentinel License Manager", "vendor": "Gemalto", "type": "Software", "credentials": "0"},
    {"product": "SymDec 4", "vendor": "General Electric", "type": "Video Streaming Recorder", "credentials": "Software:\n    admin:admin, 12345 (Log In Password), Hardware: 0000 (Advanced Menu \n    Password), 8111 (Factory Password), 1111 (Ethernet Access Reset \n    Password), 2222 (DDNS Password)"},
    {"product": "WebServer", "vendor": "General Electric", "type": "Video Streaming Recorder", "credentials": "Software:\n    admin:admin, 12345 (Log In Password), Hardware: 0000 (Advanced Menu \n    Password), 8111 (Factory Password), 1111 (Ethernet Access Reset \n    Password), 2222 (DDNS Password)"},
    {"product": "SymNav", "vendor": "General Electric", "type": "Video Streaming Recorder", "credentials": "Software:\n    admin:admin, 12345 (Log In Password), Hardware: 0000 (Advanced Menu \n    Password), 8111 (Factory Password), 1111 (Ethernet Access Reset \n    Password), 2222 (DDNS Password)"},
    {"product": "Cimplicity", "vendor": "General Electric", "type": "Video Streaming Recorder", "credentials": "Software:\n    admin:admin, 12345 (Log In Password), Hardware: 0000 (Advanced Menu \n    Password), 8111 (Factory Password), 1111 (Ethernet Access Reset \n    Password), 2222 (DDNS Password)"},
    {"product": "CIMPLICITY WebView", "vendor": "General Electric", "type": "Video Streaming Recorder", "credentials": "Software:\n    admin:admin, 12345 (Log In Password), Hardware: 0000 (Advanced Menu \n    Password), 8111 (Factory Password), 1111 (Ethernet Access Reset \n    Password), 2222 (DDNS Password)"},
    {"product": "SNMP/Web Interface", "vendor": "General Electric Digital Energy", "type": "SNMP/Web Interface", "credentials": "GE:GE (Telnet, HTTP), public (SNMP community string)"},
    {"product": "FASTlab Synthesizer", "vendor": "General Electric Healthcare", "type": "Synthesizer", "credentials": "Admin:admin"},
    {"product": "TRACERlab FX2 devices (model C, MeI and N)", "vendor": "General Electric Healthcare", "type": "Synthesis module", "credentials": "admin:tracerlab (physical access required)"},
    {"product": "TRACERlab FX2 M", "vendor": "General Electric Healthcare", "type": "Chemistry Synthesizer", "credentials": "tracerlab:tracerlab (for remote access), admin:tracerlab"},
    {"product": "HiSpeed CT/i", "vendor": "General Electric Healthcare", "type": "Computed Tomography Scanner", "credentials": "root:#bigguy, ctuser:4$apps"},
    {"product": "Lightspeed QX/i", "vendor": "General Electric Healthcare", "type": "Computed Tomography Scanner", "credentials": "root:#bigguy, ctuser:4$apps"},
    {"product": "Discovery CT590 RT", "vendor": "General Electric Healthcare", "type": "Computed Tomography Scanner", "credentials": "root:#bigguy"},
    {"product": "Optima CT580", "vendor": "General Electric Healthcare", "type": "Computed Tomography Scanner", "credentials": "root:#bigguy"},
    {"product": "Datex-Ohmeda Engstrm Ventilator", "vendor": "General Electric Healthcare", "type": "Carestation Ventilators", "credentials": "23-17-21 (Super User), 34-22-14 (service-level)"},
    {"product": "IC695PNC001", "vendor": "General Electric Intelligent Platforms", "type": "PROFINET Controller", "credentials": "admin:system"},
    {"product": "IC695ECM850", "vendor": "General Electric Intelligent Platforms", "type": "IEC 61850 Client", "credentials": "admin:system"},
    {"product": "IC695ETM001", "vendor": "General Electric Intelligent Platforms", "type": "Ethernet module/programmable controller", "credentials": "system"},
    {"product": "IC695CPE305", "vendor": "General Electric Intelligent Platforms", "type": "Ethernet module/programmable controller", "credentials": "system"},
    {"product": "IC695CPE310", "vendor": "General Electric Intelligent Platforms", "type": "Ethernet module/programmable controller", "credentials": "system"},
    {"product": "IC695CPE330", "vendor": "General Electric Intelligent Platforms", "type": "Ethernet module/programmable controller", "credentials": "system"},
    {"product": "IC698ETM001", "vendor": "General Electric Intelligent Platforms", "type": "Ethernet module/programmable controller", "credentials": "system"},
    {"product": "IC698CPE010", "vendor": "General Electric Intelligent Platforms", "type": "Ethernet module/programmable controller", "credentials": "system"},
    {"product": "IC698CPE020", "vendor": "General Electric Intelligent Platforms", "type": "Ethernet module/programmable controller", "credentials": "system"},
    {"product": "IC698CRE020", "vendor": "General Electric Intelligent Platforms", "type": "Ethernet module/programmable controller", "credentials": "system"},
    {"product": "IC698CPE030", "vendor": "General Electric Intelligent Platforms", "type": "Ethernet module/programmable controller", "credentials": "system"},
    {"product": "IC698CPE040", "vendor": "General Electric Intelligent Platforms", "type": "Ethernet module/programmable controller", "credentials": "system"},
    {"product": "IC698CRE030", "vendor": "General Electric Intelligent Platforms", "type": "Ethernet module/programmable controller", "credentials": "system"},
    {"product": "IC698CRE040", "vendor": "General Electric Intelligent Platforms", "type": "Ethernet module/programmable controller", "credentials": "system"},
    {"product": "IC698CPE030", "vendor": "General Electric Intelligent Platforms", "type": "Programmable controller with built-in web server", "credentials": "user:system"},
    {"product": "IC698CPE040", "vendor": "General Electric Intelligent Platforms", "type": "Programmable controller with built-in web server", "credentials": "user:system"},
    {"product": "IC698CRE030", "vendor": "General Electric Intelligent Platforms", "type": "Programmable controller with built-in web server", "credentials": "user:system"},
    {"product": "IC698CRE040", "vendor": "General Electric Intelligent Platforms", "type": "Programmable controller with built-in web server", "credentials": "user:system"},
    {"product": "SOS iOS Client", "vendor": "General Motors (GM), Shanghai OnStar (SOS)", "type": "Software", "credentials": "0"},
    {"product": "Reliance SCADA", "vendor": "Geovap", "type": "Software", "credentials": "0"},
    {"product": "Netmonitor", "vendor": "Heatmiser", "type": "gateway between the outside world and heating system", "credentials": "admin:admin"},
    {"product": "NETLink PRO HW 1-1a-1 and FW 1. 54 and higher", "vendor": "Helmholz Systeme", "type": "Ethernet Gateway for MPI/PROFIBUS", "credentials": "NETLink PRO PoE:admin"},
    {"product": "RS20", "vendor": "Hirschmann", "type": "Switch", "credentials": "user:public, admin:private"},
    {"product": "RS30", "vendor": "Hirschmann", "type": "Switch", "credentials": "user:public, admin:private"},
    {"product": "MICE", "vendor": "Hirschmann", "type": "Switch", "credentials": "user:public, admin:private"},
    {"product": "RSP 20", "vendor": "Hirschmann", "type": "Industrial router", "credentials": "user:public, admin:private"},
    {"product": "RSP 25", "vendor": "Hirschmann", "type": "Industrial router", "credentials": "user:public, admin:private"},
    {"product": "RSP 30", "vendor": "Hirschmann", "type": "Industrial router", "credentials": "user:public, admin:private"},
    {"product": "RSP 35", "vendor": "Hirschmann", "type": "Industrial router", "credentials": "user:public, admin:private"},
    {"product": "MACH 4000 Family", "vendor": "Hirschmann", "type": "Industrial router", "credentials": "user:public, admin:private"},
    {"product": "MACH 1000 Family", "vendor": "Hirschmann", "type": "Industrial router", "credentials": "user:public, admin:private"},
    {"product": "MACH 100 Family", "vendor": "Hirschmann", "type": "Industrial router", "credentials": "user:public, admin:private"},
    {"product": "MACH 4002 Family", "vendor": "Hirschmann", "type": "Industrial router", "credentials": "user:public, admin:private"},
    {"product": "MACH104 Family Full Gigabit", "vendor": "Hirschmann", "type": "Industrial router", "credentials": "user:public, admin:private"},
    {"product": "MACH 1040 Family Full Gigabit", "vendor": "Hirschmann", "type": "Industrial router", "credentials": "user:public, admin:private"},
    {"product": "OCTOPUS 8M", "vendor": "Hirschmann", "type": "Industrial router", "credentials": "user:public, admin:private"},
    {"product": "OCTOPUS 16M", "vendor": "Hirschmann", "type": "Industrial router", "credentials": "user:public, admin:private"},
    {"product": "OCTOPUS 24M", "vendor": "Hirschmann", "type": "Industrial router", "credentials": "user:public, admin:private"},
    {"product": "EAGLE 20", "vendor": "Hirschmann", "type": "Industrial ETHERNET Firewall", "credentials": "admin:private, user:public"},
    {"product": "Classic Platform Switches", "vendor": "Hirschmann Automation and Control GmbH, a division of Belden Inc.", "type": "Network", "credentials": "user:public, admin:private"},
    {"product": "EUB-550", "vendor": "Hitachi", "type": "Ultrasound Diagnostic Scanner", "credentials": "Service Tools:SERVICETOOL"},
    {"product": "Web Controller", "vendor": "Hitachi", "type": "Controller", "credentials": "admin:1111"},
    {"product": "LK SERIES PLC", "vendor": "HollySys Automation Technologies", "type": "PLC", "credentials": "FTP blank, Telnet blank"},
    {"product": "Honeywell XL", "vendor": "Honeywell", "type": "Controller", "credentials": "Guest:guest, SysAdmin:honey"},
    {"product": "Alerton BCM-WEB", "vendor": "Honeywell", "type": "BACtalk control module, Web server and Configurator CD", "credentials": "pass"},
    {"product": "NetAXS", "vendor": "Honeywell", "type": "Access Control Unit", "credentials": "admin:admin"},
    {"product": "PIKO-Inverter 3.0, 3.6, 4.2, 5.5, 7.0, 8.3, 10.1", "vendor": "Kostal Solar", "type": "solar inverter, storage system", "credentials": "pvserver:pvwr"},
    {"product": "PIKO BA Storage System", "vendor": "Kostal Solar", "type": "solar inverter, storage system", "credentials": "pvserver:pvwr"},
    {"product": "EDS-MD 4", "vendor": "Lantronix", "type": "Medical Device Server", "credentials": "admin:PASS"},
    {"product": "EDS-MD 8", "vendor": "Lantronix", "type": "Medical Device Server", "credentials": "admin:PASS"},
    {"product": "EDS-MD 16", "vendor": "Lantronix", "type": "Medical Device Server", "credentials": "admin:PASS"},
    {"product": "L-DALI DALI Light Controller", "vendor": "LOYTEC Electronics", "type": "Multiple Devices", "credentials": "admin:loytec4u"},
    {"product": "L-INX Automation Server", "vendor": "LOYTEC Electronics", "type": "Multiple Devices", "credentials": "admin:loytec4u"},
    {"product": "L-GATE Universal Gateway", "vendor": "LOYTEC Electronics", "type": "Multiple Devices", "credentials": "admin:loytec4u"},
    {"product": "L-IP CEA-709/IP Router", "vendor": "LOYTEC Electronics", "type": "Multiple Devices", "credentials": "admin:loytec4u"},
    {"product": "L-VIS", "vendor": "LOYTEC Electronics", "type": "Multiple Devices", "credentials": "admin:loytec4u"},
    {"product": "LIOB-10x I/O Module", "vendor": "LOYTEC Electronics", "type": "Multiple Devices", "credentials": "admin:loytec4u"},
    {"product": "LIOB-x5x I/O Module", "vendor": "LOYTEC Electronics", "type": "Multiple Devices", "credentials": "admin:loytec4u"},
    {"product": "LIP-ME20X L-IP BACnet Router", "vendor": "LOYTEC Electronics", "type": "Multiple Devices", "credentials": "admin:loytec4u"},
    {"product": "LWEB-802 Building Management System", "vendor": "LOYTEC Electronics", "type": "Multiple Devices", "credentials": "admin:loytec4u"},
    {"product": "LWEB-803 Building Management System", "vendor": "LOYTEC Electronics", "type": "Multiple Devices", "credentials": "admin:loytec4u"},
    {"product": "LWEB-900 Building Management System", "vendor": "LOYTEC Electronics", "type": "Multiple Devices", "credentials": "admin:loytec4u"},
    {"product": "L-Proxy CEA-709 Gateway", "vendor": "LOYTEC Electronics", "type": "Gateway", "credentials": "admin:admin"},
    {"product": "NetBeacon Element Management Software", "vendor": "Metrobility", "type": "HMI Software", "credentials": "guest:guest, admin:admin, root:root"},
    {"product": "PLC QnUCPU QnUDVCPU", "vendor": "Mitsubishi", "type": "PLC", "credentials": "MELSEC:MELSEC"},
    {"product": "PLC QnUCPU QnUDE(H)CPU", "vendor": "Mitsubishi", "type": "PLC", "credentials": "QNUDECPU:QNUDECPU"},
    {"product": "MES3-255C-EN", "vendor": "Mitsubishi", "type": "Web server", "credentials": "ecoV:ecopass, guest:user"},
    {"product": "AirWorks AWK-3131-RCC", "vendor": "Moxa", "type": "Industrial 802.11n wireless AP/bridge/client", "credentials": "admin:root"},
    {"product": "Railway Remote I/O (ioLogik E12xx)", "vendor": "Moxa", "type": "Remote Ethernet I/O", "credentials": "HTTP on Port 9020: 1)none:root, 2)none:none"},
    {"product": "Railway Remote I/O (ioLogik E15xx)", "vendor": "Moxa", "type": "Remote Ethernet I/O", "credentials": "HTTP on Port 9020: 1)none:root, 2)none:none"},
    {"product": "Cellular Micro RTU Controller (ioLogik W53xx, ioLogik)", "vendor": "Moxa", "type": "micro RTU controller", "credentials": "administrator:blank, Telnet on port 9900 / 9000: root:root"},
    {"product": "VPort 461 Industrial Video Encoder", "vendor": "Moxa", "type": "Industrial Video Encoder", "credentials": "admin:admin, \n    \n      :"},
    {"product": "IA240 Embedded computer", "vendor": "Moxa", "type": "Embedded computers are designed for industrial, automation applications", "credentials": "telnet root:root, FTP  root:blank, PPP root:root, serial console root:root"},
    {"product": "IA241 Embedded computer", "vendor": "Moxa", "type": "Embedded computers are designed for industrial, automation applications", "credentials": "telnet root:root, FTP  root:blank, PPP root:root, serial console root:root"},
    {"product": "OnCell Central Manager", "vendor": "Moxa", "type": "Software", "credentials": "admin:admin"},
    {"product": "EDS-505A Series", "vendor": "Moxa", "type": "Switch", "credentials": "admin:"},
    {"product": "EDS-508A Series", "vendor": "Moxa", "type": "Switch", "credentials": "admin:"},
    {"product": "OnCell G3100 Series", "vendor": "Moxa", "type": "Cellular IP Gateways", "credentials": "HTTP admin:admin, HTTP Admin:Keep \n    \n      , PAP admin:"},
    {"product": "MXview", "vendor": "Moxa", "type": "Software", "credentials": "0"},
    {"product": "PCS-9611", "vendor": "Nari", "type": "PLC", "credentials": "0"},
    {"product": "3G21WB (BigPond Firmware)", "vendor": "Netcomm Wireless", "type": "Router", "credentials": "admin:admin"},
    {"product": "3G9WB (BigPond Firmware)", "vendor": "Netcomm Wireless", "type": "Router", "credentials": "admin:admin"},
    {"product": "N3G001W (Netcomm Firmware)", "vendor": "Netcomm Wireless", "type": "Router", "credentials": "admin:admin"},
    {"product": "NB14WN (Netcomm Firmware)", "vendor": "Netcomm Wireless", "type": "Router", "credentials": "admin:admin"},
    {"product": "NB5 (Netcomm Firmware)", "vendor": "Netcomm Wireless", "type": "Router", "credentials": "admin:admin"},
    {"product": "NB5Plus4 (Netcomm Firmware)", "vendor": "Netcomm Wireless", "type": "Router", "credentials": "admin:admin"},
    {"product": "NB6Plus4 (Netcomm Firmware)", "vendor": "Netcomm Wireless", "type": "Router", "credentials": "admin:admin"},
    {"product": "NB6Plus4W (Netcomm Firmware)", "vendor": "Netcomm Wireless", "type": "Router", "credentials": "admin:admin"},
    {"product": "NNB7 (Netcomm Firmware)", "vendor": "Netcomm Wireless", "type": "Router", "credentials": "admin:admin"},
    {"product": "NB9WMAXX (Netcomm Firmware)", "vendor": "Netcomm Wireless", "type": "Router", "credentials": "admin:admin"},
    {"product": "NP804N (Netcomm Firmware)", "vendor": "Netcomm Wireless", "type": "Router", "credentials": "admin:admin"},
    {"product": "NB1300 Plus 4 (Netcomm Firmware)", "vendor": "Netcomm Wireless", "type": "Router", "credentials": "admin:password"},
    {"product": "NP803N (Netcomm Firmware)", "vendor": "Netcomm Wireless", "type": "Router", "credentials": "admin:password"},
    {"product": "4G LTE Light Industrial M2M Router", "vendor": "Netcomm Wireless", "type": "Router", "credentials": "admin:password"},
    {"product": "Linear eMerge E3 Series", "vendor": "Nortek", "type": "Access Control", "credentials": "0"},
    {"product": "SuperView", "vendor": "NOVUS AUTOMATION", "type": "SCADA", "credentials": "superview:superview"},
    {"product": "AirGate-3G", "vendor": "NOVUS Automation", "type": "Dual SIM Industrial Cellular VPN Router", "credentials": "admin:admin"},
    {"product": "N1040", "vendor": "NOVUS Automation", "type": "Temperature Controller", "credentials": "1111 (ACESS PASSWORD), 9 3 2 1 (MASTER PASSWORD)"},
    {"product": "N480D", "vendor": "NOVUS Automation", "type": "Temperature Controller", "credentials": "1111 (ACESS PASSWORD), 9 3 2 1 (MASTER PASSWORD)"},
    {"product": "N960", "vendor": "NOVUS Automation", "type": "Temperature Controller", "credentials": "1111 (ACESS PASSWORD), 9 3 2 1 (MASTER PASSWORD)"},
    {"product": "N1020", "vendor": "NOVUS Automation", "type": "Temperature Controller", "credentials": "1111 (ACESS PASSWORD), 9 3 2 1 (MASTER PASSWORD)"},
    {"product": "N1040i", "vendor": "NOVUS Automation", "type": "Temperature Controller", "credentials": "1111 (ACESS PASSWORD), 9 3 2 1 (MASTER PASSWORD)"},
    {"product": "N1540", "vendor": "NOVUS Automation", "type": "Temperature Controller", "credentials": "1111 (ACESS PASSWORD), 9 3 2 1 (MASTER PASSWORD)"},
    {"product": "N2000", "vendor": "NOVUS Automation", "type": "Temperature Controller", "credentials": "1111 (ACESS PASSWORD), 9 3 2 1 (MASTER PASSWORD)"},
    {"product": "N3000", "vendor": "NOVUS Automation", "type": "Temperature Controller", "credentials": "1111 (ACESS PASSWORD), 9 3 2 1 (MASTER PASSWORD)"},
    {"product": "N120", "vendor": "NOVUS Automation", "type": "Temperature Controller", "credentials": "1111 (ACESS PASSWORD), 9 3 2 1 (MASTER PASSWORD)"},
    {"product": "Dragon Medical 360 Network Edition", "vendor": "Nuance", "type": "Medical Speech Recognition Software Solutions", "credentials": "admin:password"},
    {"product": "NS-Series\n    Programmable Terminals Web Interface (NS12-TS01-V2, NS10-TV01-V2, \n    NS8-TV01-V2, NS5-SQ11-V2, NS5-TQ11-V2 and NS5-MQ11-V2)", "vendor": "Omron", "type": "Programmable Terminals", "credentials": "default:default"},
    {"product": "CX-Supervisor", "vendor": "Omron", "type": "Software", "credentials": "0"},
    {"product": "CX-One", "vendor": "Omron", "type": "Software", "credentials": "0"},
    {"product": "CJ1M CPU Units with Ethernet Functions", "vendor": "Omron IA", "type": "PLC", "credentials": "for http: ETHERNET, for ftp: CONFIDENTIAL"},
    {"product": "PI Vision", "vendor": "OSIsoft", "type": "Software", "credentials": "0"},
    {"product": "PI Data Archive", "vendor": "OSIsoft", "type": "Software", "credentials": "0"},
    {"product": "EH-net server", "vendor": "Ouman", "type": "HMI Software", "credentials": "admin:admin"},
    {"product": "WLAN capable devices using the WPA2 Protocol", "vendor": "PEPPERL+FUCHS/ecom instruments", "type": "Network", "credentials": "0"},
    {"product": "JouleTemp", "vendor": "Phasefale Controls", "type": "PLC", "credentials": "admin:pass"},
    {"product": "Logic+", "vendor": "PHOENIX CONTACT", "type": "Software", "credentials": "admin:admin"},
    {"product": "FL SWITCH", "vendor": "PHOENIX CONTACT", "type": "Network", "credentials": "admin:admin"},
    {"product": "FL COMSERVER", "vendor": "PHOENIX CONTACT", "type": "Software", "credentials": "0"},
    {"product": "AUTOPLATE", "vendor": "PIPS Technology", "type": "license plate recognition system", "credentials": "(Telnet), wl_test:wl_test, vesstore:vesstore, ftp_boot:ftp_boot (FTP)"},
    {"product": "ICX30-HWC", "vendor": "Prosoft Technology", "type": "Industrial Cellular Gateway", "credentials": "admin:password"},
    {"product": "FactoryTalk Alarms and Events", "vendor": "Rockwell Automation", "type": "Software", "credentials": "0"},
    {"product": "1756-EN2TSC", "vendor": "Rockwell Automation / Allen-Bradley", "type": "EtherNet/IP communication module", "credentials": "Administrator:admin"},
    {"product": "1734-AENT", "vendor": "Rockwell Automation / Allen-Bradley", "type": "I/O Adapter", "credentials": "admin:password"},
    {"product": "1756-EWEB", "vendor": "Rockwell Automation / Allen-Bradley", "type": "Web Server Module", "credentials": "Administrator:"},
    {"product": "1768-EWEB", "vendor": "Rockwell Automation / Allen-Bradley", "type": "Web Server Module", "credentials": "Administrator:"},
    {"product": "9300-RADES", "vendor": "Rockwell Automation / Allen-Bradley", "type": "Industrial Modem", "credentials": "HTTP: blank:ZYPCOM, Telnet: blank:ZYPCOM, FTP: uploader:ZYPCOM, CHAP/PAP: ppp_user:ZYPCOM"},
    {"product": "9300-8EDM", "vendor": "Rockwell Automation / Allen-Bradley", "type": "Industrial Switch", "credentials": "HTTP: blank:ZYPCOM, Telnet: blank:ZYPCOM, FTP: uploader:ZYPCOM"},
    {"product": "MicroLogix 1100 Embedded Web Server", "vendor": "Rockwell Automation / Allen-Bradley", "type": "Web Server", "credentials": "guest:guest, administrator:ml1400 (MicroLogix 1400), administrator:ml1100 (MicroLogix 1100)"},
    {"product": "MicroLogix 1400 Embedded Web Server", "vendor": "Rockwell Automation / Allen-Bradley", "type": "Web Server", "credentials": "guest:guest, administrator:ml1400 (MicroLogix 1400), administrator:ml1100 (MicroLogix 1100)"},
    {"product": "PanelView Plus 6 Graphic Terminals, Firmware 6.10 or later/, PVPlus 6", "vendor": "Rockwell Automation / Allen-Bradley", "type": "SCADA", "credentials": "password"},
    {"product": "TROVIS 5590 Web Module", "vendor": "SAMSON GROUP", "type": "Web Module", "credentials": "To read data 1111:1111, To change data 4444:4444"},
    {"product": "Integrated Management System DMS", "vendor": "Samsung", "type": "Data Management Server", "credentials": "root:rkwjsdusrnth"},
    {"product": "Integrated Management System S-NET mini", "vendor": "Samsung", "type": "S-NET IMS", "credentials": "DMS Connection: 0000 or 1234"},
    {"product": "PowerLogic Series 800 Power Meter (PM800)", "vendor": "Schneider Electric", "type": "Power Monitoring Module", "credentials": "0"},
    {"product": "PowerLogic Series 800 Power Meter (PM820SD)", "vendor": "Schneider Electric", "type": "Power Monitoring Module", "credentials": "0"},
    {"product": "PowerLogic Series 800 Power Meter (PM870SD)", "vendor": "Schneider Electric", "type": "Power Monitoring Module", "credentials": "0"},
    {"product": "PowerLogic Power Meter", "vendor": "Schneider Electric", "type": "Power Monitoring Module", "credentials": "0"},
    {"product": "PowerLogic ION7550 Energy and power meter", "vendor": "Schneider Electric", "type": "Energy and power meter", "credentials": "0"},
    {"product": "PowerLogic ION7650 Energy and power meter", "vendor": "Schneider Electric", "type": "Energy and power meter", "credentials": "0"},
    {"product": "PowerLogic ION8650 Energy and power meter", "vendor": "Schneider Electric", "type": "Energy and power meter", "credentials": "0"},
    {"product": "PowerLogic Ethernet Gateway EGX100", "vendor": "Schneider Electric", "type": "Integrated gateway-server", "credentials": "Administrator:Gateway"},
    {"product": "PowerLogic Ethernet Gateway EGX300", "vendor": "Schneider Electric", "type": "Integrated gateway-server", "credentials": "Administrator:Gateway"},
    {"product": "PowerLogic EGX200 (with firmware version 5.5 or higher)", "vendor": "Schneider Electric", "type": "gateway-server", "credentials": "Administrator:admin, User 1:master, User 2:engineer, User 3:operator"},
    {"product": "PowerLogic EGX400 (with firmware version 5.5 or higher)", "vendor": "Schneider Electric", "type": "gateway-server", "credentials": "Administrator:admin, User 1:master, User 2:engineer, User 3:operator"},
    {"product": "Modicon Quantum", "vendor": "Schneider Electric", "type": "PLC", "credentials": "ftpuser/password, qbf77101/hexakisoctahedron, USER:USER"},
    {"product": "Modicon M340", "vendor": "Schneider Electric", "type": "PLC", "credentials": "ntpupdate:ntpupdate\n    (Using an FTP client, store your rules in the file:, \n    /FLASH0/wwwroot/conf/NTP/customrules), USER:USER (FTP Setup page via \n    HTTP, HTTP credentials), sysdiag:factorycast@schneider (FTP)"},
    {"product": "Modicon M340 for Ethernet", "vendor": "Schneider Electric", "type": "PLC", "credentials": "ntpupdate:ntpupdate\n    (Using an FTP client, store your rules in the file:, \n    /FLASH0/wwwroot/conf/NTP/customrules), USER:USER (FTP Setup page via \n    HTTP, HTTP credentials), sysdiag:factorycast@schneider (FTP)"},
    {"product": "Modicon Premium", "vendor": "Schneider Electric", "type": "PLC", "credentials": "FTP: sysdiag:factorycast@schneider, HTTP: USER:USER"},
    {"product": "PowerLogic PM8000 Power Meter", "vendor": "Schneider Electric", "type": "PLC", "credentials": "Physical: 0, FTP: 8000:"},
    {"product": "PowerLogic PM8240 Power Meter", "vendor": "Schneider Electric", "type": "PLC", "credentials": "Physical: 0, FTP: 8000:"},
    {"product": "PowerLogic PM8243 Power Meter", "vendor": "Schneider Electric", "type": "PLC", "credentials": "Physical: 0, FTP: 8000:"},
    {"product": "PowerLogic PM8244 Power Meter", "vendor": "Schneider Electric", "type": "PLC", "credentials": "Physical: 0, FTP: 8000:"},
    {"product": "TSX ETG 1000", "vendor": "Schneider Electric", "type": "PLC", "credentials": "HTTP Server, PAP Protocol: USER:USER, FTP: wsupgrade:wsupgrade, Serial Connection: Administrator:Gateway"},
    {"product": "ETG100", "vendor": "Schneider Electric", "type": "PLC", "credentials": "Administrator:Gateway"},
    {"product": "M258", "vendor": "Schneider Electric", "type": "PLC", "credentials": "adm:adm"},
    {"product": "Quantum NOE 771 xx", "vendor": "Schneider Electric", "type": "Ethernet Modules", "credentials": "pcfactory:pcfactory,\n    loader:fwdownload, ntpupdate:ntpupdate, sysdiag:factorycast@schneider, \n    test:testingpw, webserver:webpages, fdrusers:sresurdf, \n    nic2212:poiuypoiuy, nimrohs2212:qwertyqwerty, nip2212:fcsdfcsd, \n    noe77111_v500:RcSyyebczS (password hashed), AUTCSE:RybQRceeSd (password \n    hashed), AUT_CSE:cQdd9debez (password hashed), target:RcQbRbzRyc \n    (password hasshed), FTP and HTTP Service: USER:USERUSER, USER:USER, \n    ftpuser:ftpuser (FTP)"},
    {"product": "CitectSCADA", "vendor": "Schneider Electric", "type": "Ethernet Modules", "credentials": "pcfactory:pcfactory,\n    loader:fwdownload, ntpupdate:ntpupdate, sysdiag:factorycast@schneider, \n    test:testingpw, webserver:webpages, fdrusers:sresurdf, \n    nic2212:poiuypoiuy, nimrohs2212:qwertyqwerty, nip2212:fcsdfcsd, \n    noe77111_v500:RcSyyebczS (password hashed), AUTCSE:RybQRceeSd (password \n    hashed), AUT_CSE:cQdd9debez (password hashed), target:RcQbRbzRyc \n    (password hasshed), FTP and HTTP Service: USER:USERUSER, USER:USER, \n    ftpuser:ftpuser (FTP)"},
    {"product": "StruxureOn Gateway", "vendor": "Schneider Electric", "type": "Proxy Server", "credentials": "0"},
    {"product": "Pelco VideoXpert Enterprise", "vendor": "Schneider Electric", "type": "Other", "credentials": "0"},
    {"product": "Triconex Tricon, model 3008", "vendor": "Schneider Electric", "type": "Safety System", "credentials": "0"},
    {"product": "Simatic S7-300 (pre-2009 versions)", "vendor": "Siemens", "type": "PLC", "credentials": "Hardcoded password: Basisk:Basisk"},
    {"product": "Simatic S7-1200", "vendor": "Siemens", "type": "PLC", "credentials": "admin:blank"},
    {"product": "Simatic S7-1500", "vendor": "Siemens", "type": "PLC", "credentials": "admin:blank"},
    {"product": "Scalance X-200", "vendor": "Siemens", "type": "Industrial Ethernet Switches", "credentials": "admin:admin (HTTP), user:user (HTTP), siemens:siemens (FTP)"},
    {"product": "W788-1PRO", "vendor": "Siemens", "type": "Industrial Wireless LAN, Industrial Ethernet Switches", "credentials": "admin:admin (HTTP), user:user (HTTP), siemens:siemens (FTP)"},
    {"product": "W788-2PRO", "vendor": "Siemens", "type": "Industrial Wireless LAN, Industrial Ethernet Switches", "credentials": "admin:admin (HTTP), user:user (HTTP), siemens:siemens (FTP)"},
    {"product": "Synco living Web server OZW772  V2.0", "vendor": "Siemens", "type": "Web-server", "credentials": "Administrator:Password"},
    {"product": "Siemens WinCC 7.x", "vendor": "Siemens", "type": "HMI Software", "credentials": "winccd:winccpass, wincce:winccpass, DMUser:Data&Pass, Administrator:Administrator"},
    {"product": "Ruggedcom RMC30", "vendor": "Siemens", "type": "Industrial router", "credentials": "admin:admin, operator:operator, guest:guest"},
    {"product": "RUGGEDCOM ROX II for RX1500, RX1501, RX1510, RX1511, RX1512", "vendor": "Siemens", "type": "Ethernet Switches Layer 3 / Routers", "credentials": "root:admin (service), admin:admin (administrator), oper:oper (operator), guest:guest (guest)"},
    {"product": "RuggedSwitch RS8000", "vendor": "Siemens", "type": "Industrial router", "credentials": "admin"},
    {"product": "RuggedSwitch RS1600", "vendor": "Siemens", "type": "Industrial router", "credentials": "admin"},
    {"product": "RuggedSwitch RS900", "vendor": "Siemens", "type": "Industrial router", "credentials": "admin"},
    {"product": "Siemens ST950", "vendor": "Siemens", "type": "Intersection controller", "credentials": "root:zP2wxY4uE"},
    {"product": "Siemens Climatix", "vendor": "Siemens", "type": "PLC", "credentials": "Level\n    6 End users: 1000 (Physical), Level 4 Service operator: 2000 \n    (Physical), Level 2 OEM: 6000 (Physical), Web: ADMIN:SBTAdmin!"},
    {"product": "Sicam SGU", "vendor": "Siemens", "type": "RTU", "credentials": "642935177"},
    {"product": "Sicam SGU", "vendor": "Siemens", "type": "RTU", "credentials": "admin@root:charleM!800"},
    {"product": "SC 7000", "vendor": "Siemens", "type": "Patient Monitors Service", "credentials": "4712 (passcode, physical access required)"},
    {"product": "SC 9000XL", "vendor": "Siemens", "type": "Patient Monitors Service", "credentials": "4712 (passcode, physical access required)"},
    {"product": "Industrial Products (Multiple)", "vendor": "Siemens", "type": "Multiple", "credentials": "0"},
    {"product": "TeleControl Server Basic", "vendor": "Siemens", "type": "RTU", "credentials": "0"},
    {"product": "SWT3000", "vendor": "Siemens", "type": "Software", "credentials": "0"},
    {"product": "TIM 1531 IRC", "vendor": "Siemens", "type": "Software", "credentials": "0"},
    {"product": "Building Technologies Products", "vendor": "Siemens", "type": "Other", "credentials": "0"},
    {"product": "AirLink", "vendor": "Sierra Wireless", "type": "3G/4G gateway", "credentials": "sconsole:12345"},
    {"product": "AirLink", "vendor": "Sierra Wireless", "type": "3G/4G gateway", "credentials": "user:12345, viewer:12345"},
    {"product": "eSolar", "vendor": "Sinapsi", "type": "Web-Server for photovoltaic applications", "credentials": "admin:admin"},
    {"product": "Sunny WebBox", "vendor": "SMA Solar Technology", "type": "ICS device for data logging", "credentials": "Installer:sma"},
    {"product": "Stulz WIB 8000", "vendor": "Stulz GmbH", "type": "PLC", "credentials": "Administrator, highest authorization: ganymed, Medium authorization: kallisto, Lowest authorization: europa"},
    {"product": "TAC Xenta 500/700/911", "vendor": "TAC AB", "type": "PLC", "credentials": "root:root"},
    {"product": "TAC Xenta 913", "vendor": "TAC AB", "type": "PLC", "credentials": "root:root"},
    {"product": "TAC Xenta 511", "vendor": "TAC AB", "type": "PLC", "credentials": "root:root"},
    {"product": "TAC Xenta 527", "vendor": "TAC AB", "type": "PLC", "credentials": "root:root"},
    {"product": "Tecomat Foxtrot", "vendor": "Tecomat", "type": "PLC", "credentials": "0:0\n    (role 0) , 1:1 (role 1), 2:2 (role 2), 3:3 (role 3), 4:4 (role 4), 5:5 \n    (role 5), 6:6 (role 6), 7:7 (role 7), 8:8 (role 8), 9:9 (role 9)"},
    {"product": "ATMS.now", "vendor": "Trafficware", "type": "Advanced Traffic Management System", "credentials": "naztec:naztec"},
    {"product": "NiagaraAX (ver 1)", "vendor": "Tridium", "type": "Software for JACE-2, JACE-403 or JACE-545", "credentials": "tridium:niagara"},
    {"product": "NiagaraAX (ver 2)", "vendor": "Tridium", "type": "Software for JACE-2, JACE-403 or JACE-545", "credentials": "tridium:niagara"},
    {"product": "NiagaraAX (ver 3)", "vendor": "Tridium", "type": "Software for JACE-2, JACE-403 or JACE-545", "credentials": "tridium:niagara"},
    {"product": "Niagara", "vendor": "Tridium", "type": "Software for JACE-2, JACE-403 or JACE-545", "credentials": "tridium:niagara"},
    {"product": "BL20-E-GW-EN", "vendor": "Turck", "type": "PLC", "credentials": "HTTP: password, FTP: (unspecified hardcoded)"},
    {"product": "BL67-E-GW-EN", "vendor": "Turck", "type": "PLC", "credentials": "HTTP: password, FTP: (unspecified hardcoded)"},
    {"product": "AirControl", "vendor": "Ubiquiti", "type": "Web Management Application", "credentials": "ubnt:ubnt"},
    {"product": "AirOS", "vendor": "Ubiquiti", "type": "operation system", "credentials": "ubnt:ubnt"},
    {"product": "WAGO-I/O-SYSTEM??750", "vendor": "Wago", "type": "Controller", "credentials": "admin:wago, user:user, guest:guest"},
    {"product": "WAGO-I/O-IPC 758-870/000-xxx", "vendor": "Wago", "type": "Compact Industrial PC?", "credentials": "http, ftp:, user:user00 , administrator:, su:ko2003wa"},
    {"product": "Modular I/O-System Linux Fieldbus Coupler 750-860", "vendor": "Wago", "type": "PLC", "credentials": "root:wago , admin:wago, user:user , guest:guest"},
    {"product": "PFC200 Series", "vendor": "WAGO", "type": "PLC", "credentials": "0"},
    {"product": "SoftCare Evo Type SE10", "vendor": "WashTec", "type": "Roll-over car wash system", "credentials": "00001 (limited access), 00000 (unlimited access)"},
    {"product": "KingSCADA 3.0", "vendor": "Wellintech", "type": "Software", "credentials": "administrator:administrator (role KVAdministrator)"},
    {"product": "TDW 33", "vendor": "Westermo", "type": "Industrial Modem", "credentials": "no password, just return, Hardcoded password: n3Y9kA6otYZu8, (?? TD-36)"},
    {"product": "MRD-305-DIN", "vendor": "Westermo", "type": "Industrial router", "credentials": "admin:westermo"},
    {"product": "MRD-310", "vendor": "Westermo", "type": "Industrial router", "credentials": "admin:westermo"},
    {"product": "MRD-315", "vendor": "Westermo", "type": "Industrial router", "credentials": "admin:westermo"},
    {"product": "MRD-330", "vendor": "Westermo", "type": "Industrial router", "credentials": "admin:westermo"},
    {"product": "MRD-355", "vendor": "Westermo", "type": "Industrial router", "credentials": "admin:westermo"},
    {"product": "MRD-350", "vendor": "Westermo", "type": "Industrial router", "credentials": "admin:westermo"},
    {"product": "MRD-455", "vendor": "Westermo", "type": "Industrial router", "credentials": "admin:westermo"},
    {"product": "RedFox Series", "vendor": "Westermo", "type": "Industrial router", "credentials": "admin:westermo"},
    {"product": "Wolverine Series", "vendor": "Westermo", "type": "Industrial router", "credentials": "admin:westermo"},
    {"product": "Lynx Series", "vendor": "Westermo", "type": "Industrial router", "credentials": "admin:westermo"},
    {"product": "Falcon Series", "vendor": "Westermo", "type": "Industrial router", "credentials": "admin:westermo"},
    {"product": "Viper Series", "vendor": "Westermo", "type": "Industrial router", "credentials": "admin:westermo"},
    {"product": "Intouch", "vendor": "Wonderware", "type": "SCADA", "credentials": "Administrator:Wonderware"},
    {"product": "Historian", "vendor": "Wonderware", "type": "SQL Server", "credentials": "SQL\n    Server Login: aadbo:pwddbo, wwdbo:pwddbo, aaAdmin:pwAdmin, \n    wwAdmin:wwAdmin, aaPower:pwPower, wwPower:wwPower, aaUser:pwUser, \n    wwUser:wwUser"},
    {"product": "System Platform/Archestra", "vendor": "Wonderware", "type": "Integrated Development Environment", "credentials": "administrator:blank"},
    {"product": "IP Cameras and DVRs", "vendor": "Xiongmai Technology", "type": "Other", "credentials": "0"},
    {"product": "442SR", "vendor": "Xzeres", "type": "small wind turbine", "credentials": "MyTurbine:m442+SRt"},
    {"product": "YFGW410 gateway", "vendor": "Yokogawa", "type": "Wireless Management Station", "credentials": "admin:!admin"},
    {"product": "DX1000", "vendor": "Yokogawa", "type": "Software", "credentials": "Administrator 1:Admin1, Administrator 2:Admin2, ..., Administrator 5:Admin5, User 1:User01, ..., User 90:User90"},
    {"product": "DX1000N", "vendor": "Yokogawa", "type": "Software", "credentials": "Administrator 1:Admin1, Administrator 2:Admin2, ..., Administrator 5:Admin5, User 1:User01, ..., User 90:User90"},
    {"product": "DX2000 Advanced", "vendor": "Yokogawa", "type": "Software", "credentials": "Administrator 1:Admin1, Administrator 2:Admin2, ..., Administrator 5:Admin5, User 1:User01, ..., User 90:User90"},
    {"product": "CENTUM CS 3000 DCS", "vendor": "Yokogawa", "type": "Distributed Control System", "credentials": "CENTUM:CENTUM"},
    {"product": "EJX910A Multivariable Transmitter HART Communication Type", "vendor": "Yokogawa", "type": "Multivariable transmitter", "credentials": "YOKOGAWA. (to release the Write Protect mode),"},
    {"product": "WT 3000 Driver", "vendor": "Yokogawa", "type": "Precision Power Analyzer", "credentials": "anonymous:blank (Ethernet access)"},
    {"product": "CENTUM series and Exaopc", "vendor": "Yokogawa", "type": "OPC", "credentials": "0"},
    {"product": "Nightingale PPM3", "vendor": "Zoe Medical", "type": "Vital Sign Monitor With CO2", "credentials": "Set Dial 1 to 49, Set Dial 2 to 48, Set Dial 3 to 46"},
    
  ];

  function generateTableRows() {
    var searchTerm = searchInput.value.toLowerCase();
    var filteredData = tableData.filter(function (row) {
      return row.product.toLowerCase().includes(searchTerm) || row.vendor.toLowerCase().includes(searchTerm);
    });

    var html = '';
    filteredData.forEach(function (row) {
      html += '<tr>';
      html += '<td>' + row.product + '</td>';
      html += '<td>' + row.vendor + '</td>';
      html += '<td>' + row.type + '</td>';
      html += '<td>' + row.credentials + '</td>';
      html += '</tr>';
    });

    tableBody.innerHTML = html;
  }

  searchInput.addEventListener('input', generateTableRows);

  generateTableRows();
});
